api_platform:
    title: 'WEC API'
    description: 'Storing and accessing sermons, events and other kinds of data'
    version: '0.1.0'

    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        html: [ 'text/html' ]

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        cache_headers:
            # Automatically generate etags for API responses.
            etag: true

            # Default value for the response max age.
            max_age: 10

            # Default value for the response shared (proxy) max age.
            shared_max_age: 3600

            # Default values of the "Vary" HTTP header.
            vary: ['Accept']

            # To make all responses public by default.
            public: false

            invalidation:
                # To enable the tags-based cache invalidation system.
                enabled: false

                # URLs of the Varnish servers to purge using cache tags when a resource is updated.
                varnish_urls: []

                # To pass options to the client charged with the request.
                request_options: []

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']

