# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true
    uid:
        default_uuid_version: 7
        time_based_uuid_version: 7
    annotations:
        enabled: false
    http_method_override: false
    
    serializer:
        enable_attributes: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 2629746


    #esi: true
    #fragments: true
    php_errors:
        log: true
