security_logout:
  path: /logout
  methods: GET

wecmk_public_home:
  path: /
  host: "www.wecmk.org"
  schemes: "https"
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction

members_area_home:
  path: /members
  host: "www.wecmk.org"
  schemes: "https"
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction

sermons_redirect:
  path: /sermons
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /
    permanent: true

api:
  resource: '.'
  type: 'api_platform'
  prefix: '/api'

authentication_token:
  path: /api/authentication_token
  methods: [ 'POST' ]

login_check:
  path: /login_check