security_logout:
  path: /logout
  methods: GET

wecmk_public_home:
  path: /
  host: "www.wecmk.org"
  schemes: "https"
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction

members_area_home:
  path: /members
  host: "www.wecmk.org"
  schemes: "https"
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction

api:
  resource: '.'
  type: 'api_platform'
  prefix: '/api'

authentication_token:
  path: /api/authentication_token
  methods: [ 'POST' ]